tasks:
  - before: sudo apt-get install -y graphviz
    init: pip install -r ./requirements.txt

vscode:
  extensions:
    - almenon.arepl
    - ms-toolsai.jupyter

github:
    prebuilds:
        master: true
        pullRequests: true
        addCheck: true
        addBadge: true
        pullRequestsFromForks: true
